INSERT INTO movies(title, genre, release_year, score) VALUES ('The Shawshank Redemption', 'Drama', 1994, 9);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Godfather', 'Crime', 1972, 9);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Dark Knight', 'Action', 2008, 9);
INSERT INTO movies(title, genre, release_year, score) VALUES ('Alien', 'SciFi', 1979, 9);
INSERT INTO movies(title, genre, release_year, score) VALUES ('Total Recall', 'SciFi', 1990, 8);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Matrix', 'SciFi', 1999, 8);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Matrix Resurrections', 'SciFi', 2021, 5);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Matrix Reloaded', 'SciFi', 2003, 6);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Hunt for Red October', 'Thriller', 1990, 7);
INSERT INTO movies(title, genre, release_year, score) VALUES ('Misery', 'Thriller', 1990, 7);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Power of the Dog', 'Western', 2021, 6);
INSERT INTO movies(title, genre, release_year, score) VALUES ('Hell or High Water', 'Western', 2016, 8);
INSERT INTO movies(title, genre, release_year, score) VALUES ('The Good the Bad and the Ugly', 'Western', 1966, 9);
INSERT INTO movies(title, genre, release_year, score) VALUES ('Unforgiven', 'Western', 1992, 7);
